repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
    -   id: ruff
        args: [ --fix ]
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
    -   id: vulture
        args: ["clintrials", ".vulture_whitelist.py"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: ["numpy<2.0.0"]
        files: ^(clintrials/|tests/)

-   repo: local
    hooks:
    -   id: deptry
        name: deptry
        entry: deptry .
        language: python
        additional_dependencies: ["deptry==0.22.0"]
        pass_filenames: false
        always_run: true

    -   id: verify-api-signatures
        name: verify-api-signatures
        entry: poetry run python scripts/verify_api_signatures.py
        language: system
        pass_filenames: false
        always_run: true

    -   id: verify-pep440-version
        name: verify-pep440-version
        entry: poetry run python scripts/verify_pep440_version.py
        language: system
        pass_filenames: false
        always_run: true

    -   id: ast-ui-linter
        name: ast-ui-linter
        entry: poetry run python scripts/ast_ui_linter.py
        language: system
        files: ^(clintrials/|tests/)visualization/dashboard/views/
        pass_filenames: true
