repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
    -   id: ruff
        args: [ --fix ]
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
    -   id: vulture
        args: ["clintrials", "tests", "scripts", ".vulture_whitelist.py"]
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: poetry run mypy --explicit-package-bases
        language: system
        files: ^(clintrials/|tests/|scripts/)
        types_or: [python, pyi]
        pass_filenames: true

    -   id: deptry
        name: deptry
        entry: poetry run deptry .
        language: system
        pass_filenames: false
        always_run: true

    -   id: verify-api-signatures
        name: verify-api-signatures
        entry: poetry run python scripts/verify_api_signatures.py
        language: system
        pass_filenames: false
        always_run: true

    -   id: ast-ui-linter
        name: ast-ui-linter
        entry: poetry run python scripts/ast_ui_linter.py
        language: system
        files: ^(clintrials/|tests/)visualization/dashboard/
        pass_filenames: true
