repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
    -   id: ruff
        args: [ --fix ]

-   repo: local
    hooks:
    -   id: deptry
        name: deptry
        entry: deptry .
        language: python
        additional_dependencies: ["deptry==0.22.0"]
        pass_filenames: false
        always_run: true
