ConstantRecruitmentStream  # unused class (clintrials/core/recruitment.py:34)
QuadrilateralRecruitmentStream  # unused class (clintrials/core/recruitment.py:82)
_.register_manual  # unused method (clintrials/core/registry.py:111)
matrix_cohort_analysis  # unused function (clintrials/core/tte.py:141)
_.to_list  # unused method (clintrials/core/unified.py:43)
set_visualization_provider  # unused function (clintrials/core/viz_interface.py:74)
_.plot_outcomes  # unused method (clintrials/dosefinding/__init__.py:296)
use_ggplot  # unused variable (clintrials/dosefinding/__init__.py:296)
_._DoseFindingTrial__reset  # unused method (clintrials/dosefinding/__init__.py:373)
_._DoseFindingTrial__calculate_next_dose  # unused method (clintrials/dosefinding/__init__.py:376)
_._DoseFindingTrial__reset  # unused method (clintrials/dosefinding/__init__.py:422)
_._DoseFindingTrial__calculate_next_dose  # unused method (clintrials/dosefinding/__init__.py:425)
_._DoseFindingTrial__reset  # unused method (clintrials/dosefinding/crm.py:583)
_._DoseFindingTrial__calculate_next_dose  # unused method (clintrials/dosefinding/crm.py:588)
_.plot_toxicity_probabilities  # unused method (clintrials/dosefinding/crm.py:812)
use_ggplot  # unused variable (clintrials/dosefinding/crm.py:812)
_.observed_efficacy_rates  # unused method (clintrials/dosefinding/efficacytoxicity.py:315)
simulate_efficacy_toxicity_dose_finding_trials  # unused function (clintrials/dosefinding/efficacytoxicity.py:574)
print_dtps_verbose  # unused function (clintrials/dosefinding/efficacytoxicity.py:793)
_.solve  # unused method (clintrials/dosefinding/efftox.py:448)
use_ggplot  # unused variable (clintrials/dosefinding/efftox.py:507)
_.solve  # unused method (clintrials/dosefinding/efftox.py:616)
use_ggplot  # unused variable (clintrials/dosefinding/efftox.py:659)
_._EfficacyToxicityDoseFindingTrial__calculate_next_dose  # unused method (clintrials/dosefinding/efftox.py:843)
_._EfficacyToxicityDoseFindingTrial__reset  # unused method (clintrials/dosefinding/efftox.py:881)
_.posterior_params  # unused method (clintrials/dosefinding/efftox.py:922)
_._EfficacyToxicityDoseFindingTrial__calculate_next_dose  # unused method (clintrials/dosefinding/wagestait.py:293)
_._EfficacyToxicityDoseFindingTrial__reset  # unused method (clintrials/dosefinding/wagestait.py:361)
_.dose_allocation_mode  # unused attribute (clintrials/dosefinding/watu.py:232)
_._EfficacyToxicityDoseFindingTrial__calculate_next_dose  # unused method (clintrials/dosefinding/watu.py:265)
_._EfficacyToxicityDoseFindingTrial__reset  # unused method (clintrials/dosefinding/watu.py:319)
spending_function_pocock  # unused function (clintrials/phase3/gsd.py:16)
_.simulate  # unused method (clintrials/phase3/gsd.py:213)
owner  # unused variable (clintrials/utils.py:191)
validate_bounds  # unused function (clintrials/validation.py:52)
validate_pdf_ua_structure  # unused function (clintrials/visualization/report.py:209)
expander_label  # unused variable (clintrials/visualization/dashboard/factory.py:126)
_.argv  # unused attribute (clintrials/visualization/dashboard/launcher.py:29)
TextSection  # unused class (clintrials/visualization/models.py:10)
_.to_plotly_json  # unused method (clintrials/visualization/models.py:156)
COLORBLIND_PALETTE  # unused variable (clintrials/visualization/provider.py:11)
_.pdf_version  # unused attribute (clintrials/visualization/report.py:29)
_.page_mode  # unused attribute (clintrials/visualization/report.py:32)
_.viewer_preferences  # unused attribute (clintrials/visualization/report.py:33)
_.__iter__  # unused attribute (clintrials/visualization/report.py:53)
_.artifact  # unused method (clintrials/visualization/report.py:55)
CRMView
EffToxView
WATUView
precision

logit1
inverse_logit1
