logit1  # unused function (clintrials/core/math.py:181)
inverse_logit1  # unused function (clintrials/core/math.py:186)
ConstantRecruitmentStream  # unused class (clintrials/core/recruitment.py:36)
QuadrilateralRecruitmentStream  # unused class (clintrials/core/recruitment.py:84)
matrix_cohort_analysis  # unused function (clintrials/core/tte.py:143)
_.to_list  # unused method (clintrials/core/unified.py:44)
set_visualization_provider  # unused function (clintrials/core/viz_interface.py:48)
_.plot_outcomes  # unused method (clintrials/dosefinding/__init__.py:291)
_._reset  # unused method (clintrials/dosefinding/__init__.py:367)
_._calculate_next_dose  # unused method (clintrials/dosefinding/__init__.py:370)
_._reset  # unused method (clintrials/dosefinding/__init__.py:416)
_._calculate_next_dose  # unused method (clintrials/dosefinding/__init__.py:419)
_._reset  # unused method (clintrials/dosefinding/crm.py:583)
_._calculate_next_dose  # unused method (clintrials/dosefinding/crm.py:588)
_.plot_toxicity_probabilities  # unused method (clintrials/dosefinding/crm.py:812)
_.observed_efficacy_rates  # unused method (clintrials/dosefinding/efficacytoxicity.py:314)
simulate_efficacy_toxicity_dose_finding_trials  # unused function (clintrials/dosefinding/efficacytoxicity.py:573)
print_dtps_verbose  # unused function (clintrials/dosefinding/efficacytoxicity.py:792)
_.solve  # unused method (clintrials/dosefinding/efftox.py:448)
_.solve  # unused method (clintrials/dosefinding/efftox.py:577)
_._calculate_next_dose  # unused method (clintrials/dosefinding/efftox.py:801)
_._reset  # unused method (clintrials/dosefinding/efftox.py:839)
_.posterior_params  # unused method (clintrials/dosefinding/efftox.py:880)
_._calculate_next_dose  # unused method (clintrials/dosefinding/wagestait.py:294)
_._reset  # unused method (clintrials/dosefinding/wagestait.py:362)
_.dose_allocation_mode  # unused attribute (clintrials/dosefinding/watu.py:232)
_._calculate_next_dose  # unused method (clintrials/dosefinding/watu.py:265)
_._reset  # unused method (clintrials/dosefinding/watu.py:319)
_.argv  # unused attribute (clintrials/visualization/dashboard/launcher.py:32)
CRMView  # unused class (clintrials/visualization/dashboard/views/crm_view.py:12)
EffToxView  # unused class (clintrials/visualization/dashboard/views/efftox_view.py:12)
WATUView  # unused class (clintrials/visualization/dashboard/views/watu_view.py:9)
TextSection  # unused class (clintrials/visualization/models.py:13)
_.to_plotly_json  # unused method (clintrials/visualization/models.py:158)
_.pdf_version  # unused attribute (clintrials/visualization/report.py:37)
_.page_mode  # unused attribute (clintrials/visualization/report.py:40)
_.viewer_preferences  # unused attribute (clintrials/visualization/report.py:41)
_.__iter__  # unused attribute (clintrials/visualization/report.py:61)
_.artifact  # unused method (clintrials/visualization/report.py:63)
validate_pdf_ua_structure  # unused function (clintrials/visualization/report.py:216)
validate_version  # unused function (clintrials/validation.py:125)
validate_feature_request  # unused function (clintrials/validation.py:152)
_.set_defaults  # unused method (clintrials/core/registry.py:163)
_.add_patients  # unused method (clintrials/core/cohort.py:23)
_.simulate  # unused method (clintrials/phase3/gsd.py:217)
_.schema  # unused property (trial classes)
GSDView  # unused class (clintrials/visualization/dashboard/views/gsd_view.py:17)
WagesTaitView  # unused class (clintrials/visualization/dashboard/views/wagestait_view.py:7)
WinRatioView  # unused class (clintrials/visualization/dashboard/views/winratio_view.py:14)
to_1d_list  # unused function (clintrials/_utils.py:40)
with_beta_prior  # unused method (tests/helpers/crm.py:50)
temp_git_repo  # unused function/variable in tests/test_audit_timeline.py
setup_func  # unused function in tests/test_crm.py, tests/test_wagestait.py, tests/test_watu.py
teardown_func  # unused function in tests/test_crm.py, tests/test_wagestait.py, tests/test_watu.py
exc_type  # unused variable (tests/test_dashboard_views.py:82)
return_value  # unused attribute/mock in tests/test_dashboard_views.py, tests/test_efftox.py, tests/test_numerics.py
pds2  # unused variable (tests/test_efftox_integration.py:44)
probs2  # unused variable (tests/test_efftox_integration.py:44)
probs_exp  # unused variable (tests/test_efftox_integration.py:68)
side_effect  # unused attribute in tests/test_gsd.py
reset_called  # unused attribute in tests/test_registry.py
DecoratorRunner  # unused class (tests/test_registry.py:102)
pos_int  # unused variable (tests/test_schema.py:14)
p_response  # unused variable (tests/test_schema.py:27)
p_custom  # unused variable (tests/test_schema.py:50)
count_custom  # unused variable (tests/test_schema.py:51)
ref  # unused attribute in tests/test_utils.py, tests/test_utils_safe_simulation_caching.py
normal_method  # unused method (tests/test_verify_api_signatures.py:51)
class_m  # unused method (tests/test_verify_api_signatures.py:54)
static_m  # unused method (tests/test_verify_api_signatures.py:58)


