[mypy]
strict = True
warn_unused_ignores = True
ignore_missing_imports = True
disallow_any_unimported = False

[mypy-tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False
disallow_untyped_decorators = False

[mypy-tests.test_accessibility]
warn_unused_ignores = False

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-statsmodels.*]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True

