[mypy]
strict = True
plugins = numpy.typing.mypy_plugin
ignore_missing_imports = True
disallow_any_unimported = False

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-statsmodels.*]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True

[mypy-clintrials.visualization.*]
ignore_errors = True

[mypy-clintrials.core.*]
ignore_errors = True

[mypy-clintrials.utils]
ignore_errors = True
