[tool.poetry]
name = "clintrials"
version = "0.1.4"
description = "clintrials is a library of clinical trial designs and methods in Python"
license = "GPL-3.0"
authors = ["Kristian Brock <kristian.brock@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/brockk/clintrials"
repository = "https://github.com/brockk/clintrials"

[tool.poetry.dependencies]
python = ">=2.7,<4"
ggplot = ">=0.6.5"
matplotlib = ">=1.4.3"
numpy = ">=1.9.2"
pandas = ">=0.15.2"
scipy = ">=0.15.1"
statsmodels = ">=0.6.1"

[tool.poetry.dev-dependencies]
nose = "*"

[build-system]
requires = ["poetry-core>=1.0"]
build-backend = "poetry.core.masonry.api"
