name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore(release)')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python - --yes
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry run pip install python-semantic-release
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Release
        env:
          POETRY_VIRTUALENVS_CREATE: "false"
        run: |
          poetry run semantic-release publish
