name: Test Suite
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify-r-fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install --with dev
      - name: Generate fixtures
        run: ./tests/fixtures/generate_fixtures.sh
      - name: Check for differences
        run: git diff --exit-code tests/fixtures/

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: |
          poetry install --with dev -E viz
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - name: Install Playwright browsers
        run: poetry run playwright install chromium --with-deps
      - name: Run tests
        run: |
          poetry run pytest -q --cov=clintrials --cov-report=xml --cov-report=term
