name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ "$PYTHON_VERSION" == 3.12* ]]; then
            python -m pip install nose-py3
          else
            python -m pip install nose
          fi
          python -m pip install numpy pandas scipy matplotlib ggplot statsmodels
          python -m pip install .
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          python -m nose -s tests
